declare module 'eslint-plugin-react'
declare module 'eslint-plugin-react-hooks'
declare module 'eslint-plugin-react-refresh'
declare module '@next/eslint-plugin-next'
declare module '@react-native/eslint-plugin'
declare module 'eslint-plugin-tailwindcss'
